// vueview/src/components/Blog.vue
<template>

  <SliderComponent titulo="Blog"></SliderComponent>
  <div class="center">
    <section id="content">
      <h2 class="subheader">{{ titulo }}</h2>
      <ArticlesComponent :articles="articles"></ArticlesComponent>
    </section>
  </div>
  <SidebarComponent></SidebarComponent>
</template>

<script>
import axios from 'axios'
import {Global} from '../Global.js'
import SidebarComponent from './Sidebar.vue';
import SliderComponent from './Slider.vue';
import ArticlesComponent from './Articles.vue';

export default {
  name: "BlogComponent",
  components: {
    SidebarComponent,
    SliderComponent,
    ArticlesComponent,
  },
  mounted() {
    this.getArticles();
  },
  methods: {
    async getArticles() {
      await axios.get(this.url + "articles")
        .then(res => {
          if (res.data.status == "Goood")
            this.articles = res.data.articles
          console.log(this.articles);

        })
        .catch(
          err => {
            console.log("Error en la conex con la api " + err);
          }
        )
    }
  },
  data() {
    return {
      titulo: "Blog",
      url:Global.url,
      articles: []
    }
  }
};
</script>

// AngularView/src/app/components/blog/blog.component.ts
import { Component } from '@angular/core';
import { SliderComponent } from '../slider/slider.component';
import { SidebarComponent } from '../sidebar/sidebar.component';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { CommonModule, NgFor } from '@angular/common';
import { Global } from '../../services/global.service';
import { ArticlesComponent } from '../articles/articles.component';

@Component({
  selector: 'app-blog',
  standalone: true,
  imports: [SliderComponent, SidebarComponent, NgFor, CommonModule,ArticlesComponent],
  templateUrl: './blog.component.html',
  styleUrl: './blog.component.css',
})
export class BlogComponent {
  public url: string;
  public title: string;
  public articles!: Article[];
  constructor(private _srvArticle: ArticleService) {
    this.title = 'Bienvenido al blog';
    this.url=Global.url;
  }
  ngOnInit(): void {
      this._srvArticle.getArticles().subscribe(
        (response) => {
          if (response.articles) this.articles = response.articles;
        },
        (error) => {
          console.log(error);
        }
      )
  }
}

<app-slider [nombre]="'Blog'" [size]="'small'"></app-slider>
<div class="center">
  <section id="content">
    <h1 class="subheader">{{ title }}</h1>
    <div id="articles">
      <!-- listado articulos -->
        <app-articles [articles]="articles"></app-articles>
      <!-- añadir + articulos con js -->
    </div>
</section>
  <app-sidebar></app-sidebar>
</div>
<div class="clearfix"></div>
