// vueview/src/components/Pelicula.vue
<template>
    <article class="article-item" id="article-template">
        <div class="img-wrap">
            <img :src="pelicula.image" :alt="pelicula.titulo" />
        </div>
        <h2>{{ pelicula.titulo }}</h2>
        <span class="date" v-bind:class="{
            yeargreen: pelicula.year > 2017,
            yearred: pelicula.year <= 2017
        }">
            {{ pelicula.year }}
        </span>
        <a href="">Leer más</a>
        <div class="clearfix"></div>
    </article>
</template>

<script>
export default {
    name: "PeliculaComponent",
    props: ['pelicula'],
}
</script>

// AngularView/src/app/components/pelicula/pelicula.component.ts
import { NgClass, NgFor, NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Pelicula } from '../../models/pelicula';

@Component({
  selector: 'app-pelicula',
  standalone: true,
  imports: [NgClass, NgFor , NgIf],
  templateUrl: './pelicula.component.html',
  styleUrl: './pelicula.component.css'
})
export class PeliculaComponent {
  @Input() pelicula!:Pelicula;
}

<article
  class="article-item"
  id="article-template"
>
  <div class="img-wrap">
    <img src="{{ pelicula.image }}" alt="Paisaje" />
  </div>
  <h2>{{ pelicula.title }}</h2>
  <span class="date">Hace 5 min</span>
  <span
    class="year"
    [ngClass]="{
      'year-green': pelicula.year > 2018,
      'year-red': pelicula.year <= 2018
    }"
  >
    {{ pelicula.year }}</span
  >
  <a href="">Leer más</a>
  <div class="clearfix"></div>
</article>
