// vueview/src/components/Slider.vue
<template>
  <div id="slider" :class="{
    'slider-big': showBtn,
    'slider-small': !showBtn
  }">
    <h1>{{titulo}}</h1>
    <router-link to="/blog" class="btn-white" v-if="showBtn">Ir al blog</router-link>
  </div>
</template>

<script>
export default {
  name: "SliderComponent",
  props:["titulo","showBtn"]
};
</script>

// AngularView/src/app/components/slider/slider.component.ts
import { NgClass, NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-slider',
  standalone: true,
  imports: [NgClass, NgIf , RouterLink],
  templateUrl: './slider.component.html',
  styleUrl: './slider.component.css'
})
export class SliderComponent {
  @Input() nombre ?: string;
  @Input() size ?: string;
}

<div
  id="slider"
  [ngClass]="{
    'slider-big': !size || size == 'big',
    'slider-small': size == 'small'
  }"
>
  <h1>{{ nombre }}</h1>
  <a [routerLink]="['/home']" class="btn-white" *ngIf="!size || size=='big'">Ir al blog</a>
</div>
