// vueview/src/components/Formulario.vue
<template>
  <SliderComponent titulo="Formulario"></SliderComponent>
  <div class="center">
    <section id="content">
      <h2 class="subheader">{{ titulo }}</h2>
      <div class="usuario" v-if="user">
        <h3>{{ user.nombre }}</h3>
        <h3>{{ user.apellidos }}</h3>
        <p>{{ user.bio }}</p>
      </div>
      <form action="" class="mid-form" @submit.prevent="mostrarUsuario()">
        <div class="form-group">
          <label for="nombre" >Nombre: </label>
          <input type="text" name="nombre" v-model="user.nombre" required>
        </div>
        <div class="form-group">
          <label for="apellidos">Apellidos: </label>
          <input type="text" name="apellidos"  v-model="user.apellidos" required> 
        </div>
        <div class="form-group">
          <label for="bio">Biografía: </label>
          <textarea name="bio" id=""  v-model="user.bio" required> </textarea>
        </div>
        <div class="form-group radiobuttons">Genero:
          <input type="radio" name="genero" id="" value="hombre" v-model="user.genero"/> Hombre
          <input type="radio" name="genero" id="" value="mujer" v-model="user.genero"/> Mujer
          <input type="radio" name="genero" id="" value="otro" v-model="user.genero" checked> Otro
        </div>
        <div class="clearfix"></div>
        <input type="submit" value="Enviar" class="btn btn-success" @click="mostrarUsuario">
      </form>
    </section>
  </div>
  <SidebarComponent></SidebarComponent>
</template>

<script>
import SidebarComponent from './Sidebar.vue';
import SliderComponent from './Slider.vue';

export default {
  name: "FormularioComponent",
  components: {
    SliderComponent,
    SidebarComponent
  },
  data() {
    return {
      titulo: "Formulario",
      user:{
        nombre: "",
        apellidos:"",
        bio:"",
        genero:"",
      }
    }
  },
  methods:{
    mostrarUsuario(){
      console.log(this.user);
    }
  }
};
</script>

// AngularView/src/app/components/formulario/formulario.component.ts
import { Component } from '@angular/core';
import { SidebarComponent } from '../sidebar/sidebar.component';
import { SliderComponent } from '../slider/slider.component';
import { FormGroup, FormsModule } from '@angular/forms';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-formulario',
  standalone: true,
  imports: [SidebarComponent, SliderComponent, FormsModule, NgIf],
  templateUrl: './formulario.component.html',
  styleUrl: './formulario.component.css'
})
export class FormularioComponent {
  public user:any;
  public campo?: string;
  constructor(){
    this.user= {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    }
  }
  public onSubmit(){
    console.log(this.user);
  }
  public hasDadoClick(){
    alert("CLICKY")
  }
  public hasSalido(){
    alert("HAS SALIDO")
  }
  public hasDadoEnter(){
    alert("Has pulsado enter")
  }
}

<app-slider [nombre]="'Formulario'" [size]="'small'"></app-slider>
<div class="center">
  <section id="content">
    <h1 class="subheader">Formulario de cliente</h1>
    <div *ngIf="user.nombre">
      <h2 class="subheader">Datos al vuelo</h2>
      Nombre: {{ user.nombre }} <br />
      Apellidos: {{ user.apellidos }} <br />
      Bio: {{ user.bio }} <br />
      Gernero: {{ user.genero }}
    </div>
    <form action="" class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="nombre">Nombre: </label>
        <input
          type="text"
          id="nombre"
          name="nombre"
          #nombre="ngModel"
          [(ngModel)]="user.nombre"
          required
          pattern="[a-zA-Z]+"
        />

        <small *ngIf="!nombre.valid && nombre.touched">
          El nombre no es valido
        </small>
      </div>
      <div class="form-group">
        <label for="apellidos">Apellidos: </label>
        <input
          type="text"
          name="apellidos"
          id="apellidos"
          #apellidos="ngModel"
          [(ngModel)]="user.apellidos"
          required
        />
        <small *ngIf="!apellidos.valid && apellidos.touched">
          Los apellidos no es valido
        </small>
      </div>
      <div class="form-group">
        <label for="bio">Biografía: </label>
        <textarea
          name="bio"
          id="bio"
          #bio="ngModel"
          [(ngModel)]="user.bio"
          required
        ></textarea>
        <small *ngIf="!bio.valid && bio.touched">
          La bio no es valida
        </small>
      </div>
      <div class="form-group radiobuttons">
        <input
          type="radio"
          name="genero"
          id=""
          value="hombre"
          #genero="ngModel"
          [(ngModel)]="user.genero"
          required
        />
        Hombre
        <input
          type="radio"
          name="genero"
          id=""
          value="mujer"
          #genero="ngModel"
          [(ngModel)]="user.genero"
        />
        Mujer
        <input
          type="radio"
          name="genero"
          id=""
          value="otro"
          #genero="ngModel"
          [(ngModel)]="user.genero"
        />
        Otro
        <small *ngIf="!genero.valid && genero.touched">
          El genero no es valido
        </small>
      </div>
      <div class="clearfix"></div>
      <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid"/>
    </form>
    <h2 class="subheader">Eventos</h2>
    <h4>Clicky</h4>
    <button (click)="hasDadoClick()" >Haz click</button> <br><br>
    <hr >
    <h4>Copia texto + perdida de foco</h4>
    <input type="text" [(ngModel)]="campo" (blur)="hasSalido()" >
    {{campo}}
    <hr>
    <h4>Pulsa enter</h4>
    <input type="text" (keyup.enter)="hasDadoEnter()" >
  </section>
  <app-sidebar></app-sidebar>
</div>
<div class="clearfix"></div>
