// vueview/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="navblog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href="" class="btn btn-success">Crear articulo</a>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el articulo</p>
      <form action="">
        <input type="text" name="search" id="" />
        <input type="submit" value="Buscar" name="submit" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "SidebarComponent",
};
</script>

// AngularView/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { ArticlesComponent } from '../articles/articles.component';
import { Article } from '../../models/article';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class SidebarComponent {
}

<aside id="sidebar">
    <div id="navblog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a [routerLink]="['/blog/crear']" class="btn btn-success">Crear articulo</a>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el articulo</p>
      <form action="" #searchForm="ngForm" (ngSubmit)="goSearch()">
        <input type="text" name="search" id="" [(ngModel)]="searchString"/>
        <input type="submit" value="Buscar" name="submit" class="btn" />
      </form>
    </div>
</aside>
