// AngularView/src/app/components/articles/articles.component.ts
import { Component, Input } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import { Global } from '../../services/global.service';
import { CommonModule } from '@angular/common';
import { Article } from '../../models/article';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-articles',
  standalone: true,
  imports: [NgIf, NgFor, CommonModule, RouterLink],
  templateUrl: './articles.component.html',
  styleUrl: './articles.component.css'
})
export class ArticlesComponent {
  @Input() articles!: Article[];
  public url:string;
  constructor(){
    this.url=Global.url
  }
}

<div *ngIf="!articles">
    Cargando...
</div>
<div id="articles" *ngIf="articles">
  <article
    class="article-item"
    id="article-template"
    *ngFor="let article of articles"
  >
    <div class="img-wrap" *ngIf="article">
      <img
        src="{{ url + 'get-image/' + article.image }}"
        alt="{{ article.image }}"
        *ngIf="article.image"
      />
      <img
        src="../../../assets/images/default.jpg"
        alt="pfp"
        *ngIf="!article.image"
      />
    </div>
    <h2>{{ article.title }}</h2>
    <span class="date">{{ article.date | date : "dd/MM/yyyy" }}</span>
    <a [routerLink]="['/blog/articulo/' , article._id]" >Leer más</a>
    <div class="clearfix"></div>
  </article>
</div>

// vueview/src/components/Articles.vue
<template>
  <div class="articles-list" v-if="articles && articles.length>=1">
    <article class="article-item" v-for="article in articles" v-bind:key="article._id">
      <div class="img-wrap">
        <img :src="this.url + 'get-image/' + article.image" alt="Paisaje" />
      </div>
      <router-link :to="{name: 'article', params:{id: article._id}}">
        <h2>{{ article.title }}</h2>
      </router-link>
      <span class="date">{{ article.date }}</span>
      <a href="">Leer más</a>
      <div class="clearfix"></div>
    </article>
  </div>
  <div v-else> CARGANDO .....</div>
</template>

<script>
import {Global} from '../Global.js'
export default{
  name: "ArticlesComponent",
  props:["articles"],
  data() {
    return {
      url:Global.url,
    }
  }
};

</script>
